-- 코드를 입력하세요
WITH INFO AS (
SELECT  CART_ID
        , GROUP_CONCAT(NAME) ITEM
FROM    CART_PRODUCTS
GROUP BY 1
)
SELECT  CART_ID
FROM    INFO
WHERE   ITEM LIKE "%Yogurt%"
        AND ITEM LIKE "%Milk%"
ORDER BY 1
