-- 코드를 입력하세요

WITH TOTAL_SUM AS(
SELECT  CAR_ID
        , COUNT(CAR_ID) AS TOTAL
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE   DATE_FORMAT(START_DATE,"%Y-%m") >= "2022-08" AND
        DATE_FORMAT(START_DATE,"%Y-%m") <= "2022-10"
GROUP BY 1
),
DATE AS (
SELECT  MONTH(START_DATE) AS MONTH
        , CAR_ID
        , COUNT(CAR_ID) AS RECORDS
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE   DATE_FORMAT(START_DATE,"%Y-%m") >= "2022-08" AND
        DATE_FORMAT(START_DATE,"%Y-%m") <= "2022-10"
GROUP BY 1,2
)
SELECT  D.MONTH
        , D.CAR_ID
        , D.RECORDS
FROM DATE D
    INNER JOIN TOTAL_SUM T
        ON D.CAR_ID = T.CAR_ID
WHERE   T.TOTAL >= 5
ORDER BY 1, 2 DESC