-- 코드를 입력하세요
# SELECT  DATE_FORMAT(O.SALES_DATE,"%Y") YEAR
#         , DATE_FORMAT(O.SALES_DATE,"%c") MONTH
#         , U.GENDER
#         , COUNT(DISTINCT O.USER_ID) USERS
# FROM    USER_INFO U
#     INNER JOIN ONLINE_SALE O
#         ON U.USER_ID = O.USER_ID
# WHERE U.GENDER IS NOT NULL
# GROUP BY 1,2,3
# ORDER BY 1,2,3

SELECT   
    YEAR(os.SALES_DATE) AS YEAR,  
    MONTH(os.SALES_DATE) AS MONTH,  
    ui.GENDER,  
    COUNT(DISTINCT os.USER_ID) AS USERS  
FROM   
    ONLINE_SALE os  
JOIN   
    USER_INFO ui ON os.USER_ID = ui.USER_ID  
WHERE   
    ui.GENDER IS NOT NULL  
GROUP BY   
    YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER  
ORDER BY   
    YEAR, MONTH, GENDER;  