-- 코드를 입력하세요
WITH TOTAL_USER AS(
    SELECT  COUNT(DISTINCT USER_ID) TOTAL_USER
    FROM    USER_INFO
    WHERE   YEAR(JOINED) = 2021
)
SELECT  YEAR(S.SALES_DATE) YEAR
        , MONTH(S.SALES_DATE) MONTH
        , COUNT(DISTINCT U.USER_ID) PURCHASED_USERS
        , ROUND(COUNT(DISTINCT U.USER_ID) / T.TOTAL_USER, 1) PUCHASED_RATIO
FROM    TOTAL_USER T, ONLINE_SALE S
    INNER JOIN USER_INFO U
        ON S.USER_ID = U.USER_ID
WHERE   YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH