SELECT  a.AUTHOR_ID
        ,a.AUTHOR_NAME
        ,b.CATEGORY
        ,SUM(b.PRICE * s.SALES) TOTAL_SALES
FROM    BOOK b
    INNER JOIN  AUTHOR a
        ON  b.AUTHOR_ID = a.AUTHOR_ID
    INNER JOIN  BOOK_SALES s
        ON  b.BOOK_ID = s.BOOK_ID
WHERE  DATE_FORMAT(s.SALES_DATE,"%Y-%m") = "2022-01"
GROUP BY 1, 3
ORDER BY 1, 3 DESC