-- 코드를 입력하세요
WITH TRUCKS AS (
    SELECT  CAR_ID
            , DAILY_FEE
    FROM    CAR_RENTAL_COMPANY_CAR
    WHERE   CAR_TYPE = "트럭"
)
, TRUCK_DISCOUNT AS (
    SELECT  CAST(SUBSTRING(DURATION_TYPE, 1 , LOCATE("일",DURATION_TYPE) - 1) AS UNSIGNED) AS DURATION
            , DISCOUNT_RATE
    FROM    CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE   CAR_TYPE = "트럭"
)
, TRUCK_HISTORY AS (
    SELECT  H.HISTORY_ID
            , H.CAR_ID
            , T.DAILY_FEE 
            , DATEDIFF(H.END_DATE, H.START_DATE) + 1 DATE
            ,  (
                SELECT  D.DISCOUNT_RATE  
                FROM    TRUCK_DISCOUNT D  
                WHERE   DATE >= D.DURATION  
                ORDER BY D.DURATION DESC  
                LIMIT 1  
            ) AS DISCOUNT_RATE  
    FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        INNER JOIN TRUCKS T
            ON H.CAR_ID = T.CAR_ID
)
SELECT  HISTORY_ID
        , FLOOR(DATE * DAILY_FEE * (1 - COALESCE(DISCOUNT_RATE, 0)/100)) FEE
FROM    TRUCK_HISTORY
ORDER BY FEE DESC, HISTORY_ID DESC