-- 동물 수 구하기
SELECT  COUNT(*)
FROM    ANIMAL_INS

-- 동명 동물 수 구하기
SELECT  NAME
        , COUNT(NAME) AS COUNTER
FROM    ANIMAL_INS
GROUP BY 1
HAVING  NOT NAME = '' AND COUNT(NAME) > 1
ORDER BY 1

-- 아픈 동물 찾기
SELECT  NAME
        , COUNT(NAME) AS COUNTER
FROM    ANIMAL_INS
GROUP BY 1
HAVING  NOT NAME = '' AND COUNT(NAME) > 1
ORDER BY 1

-- 상위 n개 레코드
SELECT  NAME
FROM    ANIMAL_INS
WHERE   DATETIME = 
(
SELECT  MIN(DATETIME)
FROM    ANIMAL_INS
)

-- 최솟값 구하기
SELECT  MIN(DATETIME)
FROM    ANIMAL_INS

-- 어린 동물 찾기
SELECT  ANIMAL_ID
        , NAME
FROM    ANIMAL_INS
WHERE   INTAKE_CONDITION <> 'Aged'
ORDER BY 1

-- 여러 기준 정렬
SELECT  ANIMAL_ID
        , NAME
        , DATETIME
FROM    ANIMAL_INS
ORDER BY 2, 3 DESC

-- 이름에 el이 들어간 동물 찾기
SELECT  ANIMAL_ID
        , NAME
FROM    ANIMAL_INS
WHERE   NAME LIKE '%el%' AND ANIMAL_TYPE = 'Dog'
ORDER BY 2

-- Null 처리
SELECT  ANIMAL_TYPE
        , IF(NAME IS NULL ,'No name',NAME) AS NAME
        , SEX_UPON_INTAKE
FROM    ANIMAL_INS

-- 나이 정보가 없는 회원 수 
SELECT  COUNT(*) AS USERS
FROM    USER_INFO
WHERE   AGE IS NULL

-- 가장 비싼 상품
SELECT  MAX(PRICE) AS MAX_PRICE
FROM    PRODUCT